version: '3.8'
services:
  app:
    image: ai_agent_yandexgpt:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
